#!/bin/bash

if [ ! -d installers/usr ];then
  mkdir installers/usr
fi

if [ ! -d installers/usr/bin ];then
  mkdir installers/usr/bin
fi

cd terminatord
./configure || exit 1
make || exit 1
cp bin/Release/terminatord ../installers/usr/bin/
cd ..

fakeroot dpkg-deb --build installers terminatord.deb
