import os
env=Environment(LIBS = ['pthread'])
if 'CPPFLAGS' in os.environ:
    env.Append(CPPFLAGS = os.environ['CPPFLAGS'])

if 'CXXFLAGS' in os.environ:
    env.Append(CXXFLAGS = os.environ['CXXFLAGS'])

if 'CCFLAGS' in os.environ:
    env.Append(LDFLAGS = os.environ['CCFLAGS'])

if 'LDFLAGS' in os.environ:
    env.Append(LDFLAGS = os.environ['LDFLAGS'])

env.Append(CXXFLAGS = ["--std=c++0x"])
env.ParseConfig('pkg-config --cflags --libs libprocps')

terminatord = env.Program('terminatord', ['main.cpp', Glob('src/*.cpp')])
env.Install('/usr/bin', terminatord)
env.Alias('install', '/usr/bin')
